### ISSUE TITLE
7.26- 8.02 Progress Report

### ISSUE THREAD

**Issue by AlexiaChen** [AlexiaChen/revisit-harmony-final-coding-question#1]
# Report

## Tasks

- [x]  Confirm getLogs and getBlocks if it leading CPU spike issue on testnet
 
Tested on local  it was indeed lead CPI spike issue when I requrest large range block with curl

run with explorer node:

```bash
./harmony --run=explorer --run.shard 0
```

run curl with large block range:

```bash
#  block range is 58802 = 0xbce5b2 - 0xbc0000
curl -d '{ "jsonrpc":"2.0", "method":"hmy_getLogs", "params":[ { "fromBlock":"0xbc0000", "toBlock":"0xbce5b2" } ], "id":1 }' -H "Content-Type:application/json" -X POST "http://127.0.0.1:9500"
```

```bash
# block range is 58802 = 0xbce5b2 - 0xbc0000
curl -d '{ "jsonrpc":"2.0", "method":"eth_getLogs", "params":[ { "fromBlock":"0xbc0000", "toBlock":"0xbce5b2" } ], "id":1 }' -H "Content-Type:application/json" -X POST "http://127.0.0.1:9500"
```

result:

When the request is executed, you can see from the `top` command that both memory and CPU spike up for a short time, and only after the request is completed and the json is returned, the CPU decreases to its normal value

Tested on testnet , it was indeed lead CPU spike :

![图片](https://user-images.githubusercontent.com/8574915/127789620-7067d503-95be-462c-a344-aeeeb666b0ce.png)

When I close the request, the CPU usage starts to drop

![图片](https://user-images.githubusercontent.com/8574915/127789636-6039326d-c6c9-40a6-a5c1-90cf0efc166b.png)

- [x] for RPC slow response https://github.com/harmony-one/harmony/issues/3831

Just reconfirmed with Soph,  those data come from the canary test, directly from AWS. it's not a measurement done on the node itself.. So, it's not a data with wrong used the metrics I provided. So finally need to do comparision with the measurement  of the node itself to check the problem

- [ ] eth_getLogs/hmy_getLogs rpcs fail with json error for larger block ranges (pending)

Jacky and I replied message to ganesha, But according to ganesha's response, it seems to be necessary to meet such needs, Does this requirement need to be handed over to Jacky to investigate?

- [ ] continuely working on root cause of OOM (doing)

Posted a issue on official libp2p Kad DHT repo, but there is no response from now, 

   - [ ] plan to recheck kad dht code and yamux-stream code (pending)
